<?php

/**
 * @file
 * Contains views_path.module..
 */

/**
 * Implements hook_views_data_alter().
 */
function views_path_views_data_alter(array &$data) {
  $entity_types = \Drupal::entityTypeManager()->getDefinitions();
  foreach ($entity_types as $entity_type_id => $entity_type) {
    $base_table = $entity_type->getBaseTable();
    if (empty($base_table)
      || empty($data[$base_table])
      || !empty($data[$base_table]['views_path'])
    ) {
      continue;
    }

    $t_arguments = ['@entity_type_label' => $entity_type->getLabel()];
    $data[$base_table]['views_path'] = [
      'field' => [
        'title' => t('Entity path', $t_arguments),
        'help' => t('The aliased path to this @entity_label',
          ['@entity_label' => $entity_type->getLabel()]),
        'id' => 'views_path',
      ],
    ];
  }
}
